#All env variables saved in config file 
#Wed Jun 21 17:18:50 IST 2023
albatross-url=https\://albatross-neo-mr.recruitcrm.io/v1/
auditLog-url=https\://neo-mr-audit-log.recruitcrm.io/v1/auditlogs/
baseURI=https\://neo-mr.recruitcrm.net/actions
env=https\://neo-mrapi.recruitcrm.io/v1/
executiveSummaryServiceURL=https\://neo-mr-executive-search-report.recruitcrm.io/v1/
hiring-pipeline-Service-url=https\://neo-mr-hiring-pipeline.recruitcrm.io/v1/
job-board-Service-url=https\://neo-mr-jobboard.recruitcrm.io/v1
logicmelon_apikey=FF308D89-E1E2-4303-94D4-BB87D7A2F230
logicmelon_password=RecruitCRM111
logicmelon_username=parthib@recruitcrm.io
nyma-url=https\://neo-mrnyma.recruitcrm.io/v2/
report-service-url=https\://neo-mr-report.recruitcrm.io/v1/
token=AFOT560N-BjcHXdbqpz-qcrI09izs7-Yai1ngQUQpJQczcSlY0NkLkEJWEWMhYBZvpbVqPgacPR_CqMhkd7bJF8xNTkzNDA4NTc5
url=https\://neo-mr.recruitcrm.net//
version=v2/
