package io.rcrm.api.listeners;

import org.testng.IAlterSuiteListener;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlInclude;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Restructures a group-based TestNG suite so that each test method runs
 * in its own {@code <test>} block — exactly like the hand-written profile
 * XMLs (e.g. invoiceService.xml).  This gives every method a fresh class
 * instance, a fresh {@code @BeforeClass} lifecycle (fresh Reaper account),
 * and a fresh DataProvider invocation, eliminating cross-method data
 * pollution that causes count mismatches, stale-entity 404s, and
 * token-context 401s during group execution.
 *
 * The listener only activates when the suite contains group filters
 * (i.e. it was generated by {@code -DtestGroup=...}).  Profile-based
 * execution (which already has per-method test blocks) is unaffected.
 *
 * <p>{@code nightly-build} is <b>not</b> altered here — Surefire/TestNG run it with
 * {@code parallel=classes} (see {@code group-parallel} profile), one instance per class, group filter
 * on methods. Rebuilding thousands of {@code <test>} nodes for ~4k methods blew heap and CPU; that path
 * is unlike {@code regression.xml}, which is a hand-written suite with a curated method list.
 *
 * <p>Parallelism for {@code -DtestGroup=...} is controlled by Surefire {@code threadCount}
 * in the {@code group-parallel} Maven profile ({@code perCoreThreadCount=false} so the count
 * is not multiplied by CPU cores). Override with {@code -DthreadCount=N}.
 */
public class MethodIsolationListener implements IAlterSuiteListener {

    private static final String ARIES_SERVICE_SMOKE_GROUP = "aries_service_smoke";
    private static final String NIGHTLY_BUILD_GROUP = "nightly-build";

    @Override
    public void alter(List<XmlSuite> suites) {
        for (XmlSuite suite : suites) {
            List<XmlTest> originalTests = new ArrayList<>(suite.getTests());

            boolean hasGroupFilter = originalTests.stream()
                    .anyMatch(t -> t.getIncludedGroups() != null
                            && !t.getIncludedGroups().isEmpty());
            if (!hasGroupFilter) {
                return;
            }

            // Large suites: let TestNG + Surefire handle groups natively (parallel=classes in pom).
            if (isSingleIncludedGroup(originalTests, ARIES_SERVICE_SMOKE_GROUP)
                    || isSingleIncludedGroup(originalTests, NIGHTLY_BUILD_GROUP)) {
                return;
            }

            suite.setParallel(XmlSuite.ParallelMode.TESTS);
            suite.setThreadCount(resolveThreadCount());

            for (XmlTest originalTest : originalTests) {
                List<String> includedGroups = originalTest.getIncludedGroups();
                if (includedGroups == null || includedGroups.isEmpty()) {
                    continue;
                }

                for (XmlClass xmlClass : originalTest.getClasses()) {
                    splitClassIntoMethodTests(suite, xmlClass, includedGroups);
                }
            }

            suite.getTests().removeAll(originalTests);
        }
    }

    private void splitClassIntoMethodTests(XmlSuite suite,
                                           XmlClass xmlClass,
                                           List<String> includedGroups) {
        Class<?> clazz;
        try {
            clazz = Class.forName(xmlClass.getName());
        } catch (ClassNotFoundException e) {
            System.err.println("[MethodIsolationListener] Class not found: "
                    + xmlClass.getName());
            return;
        }

        List<Method> matchingMethods = new ArrayList<>();
        for (Method method : clazz.getMethods()) {
            Test testAnnotation = method.getAnnotation(Test.class);
            if (testAnnotation != null && hasMatchingGroup(testAnnotation, includedGroups)) {
                matchingMethods.add(method);
            }
        }

        if (matchingMethods.isEmpty()) {
            return;
        }

        boolean hasDependencies = matchingMethods.stream()
                .anyMatch(m -> m.getAnnotation(Test.class).dependsOnMethods().length > 0);

        if (hasDependencies) {
            createClassLevelTest(suite, xmlClass, matchingMethods, includedGroups);
        } else {
            for (Method method : matchingMethods) {
                createMethodLevelTest(suite, xmlClass, method, includedGroups);
            }
        }
    }

    /**
     * One {@code <test>} per method — full method-level isolation.
     */
    private void createMethodLevelTest(XmlSuite suite,
                                       XmlClass xmlClass,
                                       Method method,
                                       List<String> includedGroups) {
        XmlTest test = new XmlTest(suite);
        test.setName(xmlClass.getName() + "." + method.getName());
        test.setIncludedGroups(includedGroups);
        XmlClass newClass = new XmlClass(xmlClass.getName());
        newClass.setIncludedMethods(
                Collections.singletonList(new XmlInclude(method.getName())));
        test.setClasses(Collections.singletonList(newClass));
    }

    /**
     * Fallback for classes with {@code dependsOnMethods} — all matching
     * methods stay in a single {@code <test>} block so TestNG can
     * resolve the dependency chain.
     */
    private void createClassLevelTest(XmlSuite suite,
                                      XmlClass xmlClass,
                                      List<Method> methods,
                                      List<String> includedGroups) {
        XmlTest test = new XmlTest(suite);
        test.setName(xmlClass.getName() + " (class-level)");
        test.setIncludedGroups(includedGroups);
        XmlClass newClass = new XmlClass(xmlClass.getName());
        List<XmlInclude> includes = methods.stream()
                .map(m -> new XmlInclude(m.getName()))
                .collect(Collectors.toList());
        newClass.setIncludedMethods(includes);
        test.setClasses(Collections.singletonList(newClass));
    }

    private boolean hasMatchingGroup(Test testAnnotation, List<String> groups) {
        for (String methodGroup : testAnnotation.groups()) {
            if (groups.contains(methodGroup)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Match {@code regression.xml} ({@code thread-count="25"}): cap TestNG workers when running by group.
     * Reads {@code -DthreadCount} / Surefire {@code systemPropertyVariables.threadCount} (pom default 25).
     */
    private static int resolveThreadCount() {
        String raw = System.getProperty("threadCount");
        if (raw == null || raw.isBlank()) {
            return 25;
        }
        try {
            int n = Integer.parseInt(raw.trim());
            return n > 0 ? n : 25;
        } catch (NumberFormatException e) {
            System.err.println("[MethodIsolationListener] Invalid threadCount='" + raw + "', using 25");
            return 25;
        }
    }

    private static boolean isSingleIncludedGroup(List<XmlTest> tests, String groupName) {
        for (XmlTest test : tests) {
            List<String> included = test.getIncludedGroups();
            if (included == null || included.isEmpty()) {
                continue;
            }
            return included.size() == 1 && groupName.equals(included.get(0));
        }
        return false;
    }
}
